[package]
name = "hello-wasm"
version = "0.0.0"
authors = ["gurv <vladimir.gurinovich@gmail.com>"]
description = "A sample project with wasm-pack"
license = "MIT/Apache-2.0"
repository = "https://github.com/gurv/vg-rust-hello"
edition = "2018"

[lib]
# crate-type = ["cdylib"]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2"
hello-lib = { path = "../hello-lib" }